'use strict';
const assert=require('node:assert/strict');
const {scheduledISO,readReceipt,persistReceipt,RECEIPT_KEY}=require('../sale-comments.js');
const memory=new Map();const storage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)};
const receipt={id:'receipt-123',path:'/sale-comments/campaigns',body:{previewId:'p1'}};
persistReceipt(storage,receipt);assert.deepEqual(readReceipt(storage),receipt);
assert.throws(()=>persistReceipt(storage,{...receipt,id:'other'}),/前回/);
assert.throws(()=>persistReceipt({getItem:()=>null,setItem:()=>{}},receipt),/保存/);
memory.set(RECEIPT_KEY,'not-json');assert.throws(()=>readReceipt(storage));
assert.equal(scheduledISO('2099-01-01T09:30'),'2099-01-01T00:30:00.000Z');
assert.throws(()=>scheduledISO('2020-01-01T10:30'),/未来/);
assert.throws(()=>scheduledISO('bad'),/日時/);
console.log('PASS sale receipts: persistence, duplicate/corrupt storage blocking, JST scheduling');
