'use strict';
const assert = require('node:assert/strict'), fs = require('node:fs'), vm = require('node:vm'), crypto = require('node:crypto');
const engine = require('../background-template.js');
const n=320*320, prediction=new Float32Array(n);
for(let y=40;y<280;y++)for(let x=70;x<250;x++)prediction[y*320+x]=0.95;
const mask=engine.normalizedMask(prediction);
assert.deepEqual(engine.bounds(mask,320,320),{left:70,top:40,right:249,bottom:279});
for(const data of [new Float32Array(1),new Float32Array(n).fill(1),new Float32Array(n).fill(NaN)])assert.throws(()=>engine.normalizedMask(data));
const painted=mask.slice();engine.paintMask(painted,5,5,4,255);assert.equal(painted[5*320+5],255);engine.paintMask(painted,5,5,4,0);assert.equal(painted[5*320+5],0);assert.equal(mask[5*320+5],0,'edit copies do not alter initial mask');
const fit=engine.fit(engine.bounds(mask,320,320),720,1280,84,1080);
assert.ok(fit.dx>=0&&fit.dy>=0);assert.ok(Math.max(fit.dw,fit.dh)<=1080*.841);
assert.ok(Math.abs(fit.dw/fit.dh-fit.w/fit.h)<1e-9,'retain proportions');
assert.throws(()=>engine.bounds(new Uint8Array(n),320,320));
assert.equal(crypto.createHash('md5').update(fs.readFileSync('models/u2netp.onnx')).digest('hex'),'8e83ca70e441ab06c318d82300c84806');
const html=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8');
for(const asset of ['background-template.js','background-worker.js','assets/backgrounds/white-carpet-ivy.png','models/u2netp.onnx','vendor/onnxruntime/ort-wasm-simd-threaded.wasm'])assert.ok(sw.includes(asset));
assert.match(html,/script-src 'self' 'wasm-unsafe-eval'/);assert.doesNotMatch(html,/script-src[^;]*(?:'unsafe-eval'|'unsafe-inline')/);
const nodes=new Map();function node(id){if(!nodes.has(id))nodes.set(id,{value:'84',textContent:'',disabled:false,close(){},focus(){},classList:{toggle(){}},querySelectorAll(){return[];}});return nodes.get(id);}
const ctx={console:{...console,error(){}},URL,AbortController,setTimeout,clearTimeout,__MERCARI_TEST__:true,localStorage:{getItem(){return null},setItem(){},removeItem(){}},document:{getElementById:node,querySelectorAll(){return[]}},MercariBackgroundTemplate:{render(){return {}},cutout:async()=>mask}};
ctx.globalThis=ctx;ctx.window=ctx;vm.createContext(ctx);vm.runInContext(['catalog-data.js','photo-adjust.js','app.js'].map(f=>fs.readFileSync(f,'utf8')).join('\n'),ctx);
vm.runInContext(`setPhotoProcessingLock_=()=>{};renderPreviews=()=>{};updateGenerateButton=()=>{};scheduleSave=()=>{};updateDraftChecklist=()=>{};invalidateGeneratedResultAfterInputChange_=()=>{};showStatus=()=>{};`,ctx);
const original={mediaType:'image/jpeg',base64:'b3JpZ2luYWw=',base64HQ:'SE9vcmlnaW5hbA=='};
const newPhoto={mediaType:'image/jpeg',base64:'bmV3',base64HQ:'bmV3SFE=',dataUrl:'data:image/jpeg;base64,bmV3',originalDataUrl:'data:image/jpeg;base64,bmV3',originalBase64HQ:'bmV3SFE=',adjustSourceVersion:1,adjust:{brightness:0}};
ctx.original=original;ctx.newPhoto=newPhoto;ctx.mask=mask;
function fixture(){vm.runInContext(`uploadedImages=[original];activeTemporaryDraftId='product-a';photoProcessingInProgress=false;descriptionGenerationInProgress=false;backgroundTemplateState={photo:original,draftId:'product-a',mask,image:{},background:{}};buildBackgroundTemplatePhoto_=()=>newPhoto;`,ctx);}
fixture();ctx.applyBackgroundTemplate_();assert.equal(vm.runInContext('uploadedImages.length',ctx),2);assert.equal(vm.runInContext('uploadedImages[0]',ctx),newPhoto);assert.equal(vm.runInContext('uploadedImages[1]',ctx),original);assert.equal(vm.runInContext('backgroundTemplateState',ctx),null);
const hooks=ctx.MercariAppTestHooks;
const restored=hooks.hydrateTemporaryDraftPhoto_(hooks.compactTemporaryDraftPhoto_(newPhoto));assert.equal(restored.base64HQ,newPhoto.base64HQ);assert.equal(restored.base64,newPhoto.base64);
for(const quality of [true,false])assert.equal(hooks.buildDraftPayload_({photos:[restored],preferHighQuality:quality}).photos[0].base64,quality?newPhoto.base64HQ:newPhoto.base64);
fixture();vm.runInContext(`buildBackgroundTemplatePhoto_=()=>{throw Error('encode failure')}`,ctx);ctx.applyBackgroundTemplate_();assert.equal(vm.runInContext('uploadedImages.length',ctx),1);assert.equal(vm.runInContext('uploadedImages[0]',ctx),original);assert.equal(vm.runInContext('photoProcessingInProgress',ctx),false);
fixture();vm.runInContext(`activeTemporaryDraftId='product-b'`,ctx);ctx.applyBackgroundTemplate_();assert.equal(vm.runInContext('uploadedImages.length',ctx),1);
fixture();vm.runInContext(`uploadedImages=Array(MAX_SELECT_PHOTOS).fill(original)`,ctx);ctx.applyBackgroundTemplate_();assert.equal(vm.runInContext('uploadedImages.length===MAX_SELECT_PHOTOS',ctx),true);
fixture();vm.runInContext('descriptionGenerationInProgress=true',ctx);ctx.applyBackgroundTemplate_();assert.equal(vm.runInContext('uploadedImages.length',ctx),1);
fixture();vm.runInContext(`backgroundTemplateState.preparing=true;backgroundTemplateState.operationId=++photoProcessingOperationId;photoProcessingInProgress=true;backgroundTemplateState.abort=new AbortController();globalThis.savedAbort=backgroundTemplateState.abort;`,ctx);ctx.closeBackgroundTemplate_();assert.equal(ctx.savedAbort.signal.aborted,true);assert.equal(vm.runInContext('photoProcessingInProgress',ctx),false);
console.log('PASS background template: mask validation, aspect-preserving fit, model integrity, save/HQ transport, original retained, failed encode, stale product, limits, busy guard and cancel');
