'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const nodes = new Map();
const context = {console, URL, __MERCARI_TEST__:true, localStorage:{getItem:()=>null}, document:{getElementById:id=>{if(!nodes.has(id))nodes.set(id,{value:'',innerHTML:'',textContent:'',hidden:false});return nodes.get(id);}}};
vm.createContext(context);
vm.runInContext(fs.readFileSync('catalog-data.js','utf8')+'\n'+fs.readFileSync('app.js','utf8'),context);
const h=context.MercariAppTestHooks;
const item=(n,name,row=n)=>({inventoryUuid:`inv_550e8400-e29b-41d4-a716-${String(n).padStart(12,'0')}`,productName:name,row,asin:'なし'});
const items=[item(20,'ビームスF ストライプ シャツ 白 48'),item(19,'別ブランド デニムパンツ'),item(2,'ビームスF タートルネックニット ブラウン 50')];
const ranked=h.rankInventoryCandidates_(items,{title:'美品 BEAMS F タートルネックニット ブラウン 50',brands:['BEAMS F','ビームスF'],size:'50'});
assert.equal(ranked.suggested[0].row,2);
assert.deepEqual(Array.from(ranked.latest,x=>x.row),[20,19]);
assert.equal(h.rankInventoryCandidates_(items,{title:'ビームスF',brands:['ビームスF']}).suggested.length,0);
const many=Array.from({length:5},(_,n)=>item(n+1,'ビームスF タートルネックニット ブラウン 50'));
const limited=h.rankInventoryCandidates_([...many,many[0]],{title:many[0].productName});
assert.equal(limited.suggested.length,3);assert.equal(limited.latest.length,2);
assert.equal(h.rankInventoryCandidates_([{...items[0],asin:'B000000001'}],{}).latest.length,0);
let calls=0, release;
context.mockFetch=async()=>{calls++;return await new Promise(r=>release=r);};
vm.runInContext('getMercariServiceUrl=async()=>"https://example.test"; fetchWithTimeout=mockFetch; readJsonResponse=async r=>r;',context);
(async()=>{
 const a=h.fetchInventoryCandidates_(''); const b=h.fetchInventoryCandidates_('');
 await new Promise(setImmediate);assert.equal(calls,1);
 release({ok:true,items});await Promise.all([a,b]);
 await h.fetchInventoryCandidates_('');assert.equal(calls,1);
 const forced=h.fetchInventoryCandidates_('',{force:true});await new Promise(setImmediate);assert.equal(calls,2);release({ok:true,items});await forced;
 const search=context.document.getElementById('inventory-search-input');
 search.value='old';const old=h.loadInventoryCandidates_();await new Promise(setImmediate);const oldRelease=release;
 search.value='new';const fresh=h.loadInventoryCandidates_();await new Promise(setImmediate);release({ok:true,items:[item(99,'新しい検索結果')]});await fresh;
 oldRelease({ok:true,items:[item(98,'古い検索結果')]});await old;
 assert.match(nodes.get('inventory-candidate-list').innerHTML,/新しい検索結果/);
 assert.doesNotMatch(nodes.get('inventory-candidate-list').innerHTML,/古い検索結果/);
 const fail=h.loadInventoryCandidates_({force:true});await new Promise(setImmediate);release({ok:false,error:'offline'});await assert.rejects(fail);
 assert.match(nodes.get('inventory-candidate-list').innerHTML,/新しい検索結果/);
 assert.match(nodes.get('inventory-candidate-status').textContent,/前回の一覧/);
 console.log('Inventory ranking, manual selection boundary, cache, deduplication, stale search and recovery passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
